name: Run ClickHouse SQL Scripts

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  run-sql:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: download ClickHouse locally
      run: |
        curl https://clickhouse.com/ | sh
    
    - name: Run SQL Scripts
      run: |       
        for file in ./sql/*.sql; do
          ./clickhouse client --host gns0hl2of0.us-east-1.aws.clickhouse.cloud --secure --password 'z5KNWZt~yddf_' --queries-file file
        done
