name: Run ClickHouse SQL Scripts

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  run-sql:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Add the ClickHouse APT Repository
      run: |
        sudo add-apt-repository 'deb http://ppa.launchpad.net/yandex-clickhouse/clickhouse-server/ubuntu 20.04 main'
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5860E57C


    - name: Install ClickHouse Client
      run: |
        sudo apt update
        sudo apt install clickhouse-client
        clickhouse-client --version

    # - name: Run SQL Scripts
    #   run: |
    #     for file in ./sql/*.sql; do
    #       clickhouse-client --host gns0hl2of0.us-east-1.aws --port 8443 --user default --password dQmdvuZ8Isw~t --query "$(cat $file)"
    #     done

      # working-directory: $GITHUB_WORKSPACE