name: Run ClickHouse SQL Scripts

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  run-sql:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Add the ClickHouse APT Repository
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E0C56BD4


    - name: Install ClickHouse Client
      run: |
        sudo apt update
        sudo apt install clickhouse-client
        clickhouse-client --version

    - name: Run SQL Scripts
      run: |
        for file in ./sql/*.sql; do echo "$(basename "$file")"; done
        clickhouse-client  -host gns0hl2of0.us-east-1.aws --secure --port 9440 --user default --password dQmdvuZ8Isw~t  --query "DROP DATABASE IF EXISTS new_database"
    # CREATE TABLE my_table ( id UInt32, name String  ) ENGINE = MergeTree()  ORDER BY id;

    # for file in ./sql/*.sql; do
    #   clickhouse-client --host gns0hl2of0.us-east-1.aws --port 8443 --user default --password dQmdvuZ8Isw~t --query "$(cat $file)"
    # done

      # working-directory: $GITHUB_WORKSPACE