name: Run ClickHouse SQL Scripts

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  run-sql:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: download ClickHouse locally
      run: |
        curl https://clickhouse.com/ | sh


    - name: connect to clickhouse client
      run: |
        ./clickhouse client --host gns0hl2of0.us-east-1.aws.clickhouse.cloud --secure --password 'z5KNWZt~yddf_' --query  'CREATE DATABASE db2'

    # - name: Run SQL Scripts
    #   run: |
    #     Create database IwishItllwork