name: Run ClickHouse SQL Scripts

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  run-sql:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: download ClickHouse locally
      run: |
        curl https://clickhouse.com/ | sh
    
    - name: Run SQL Scripts
      run: |       
        for file in ./sql/*.sql; do
          ./clickhouse client --host 172-233-239-201.ip.linodeusercontent.com --secure --password 'report123#' --queries-file "$file"
        done
