name: Run ClickHouse SQL Scripts

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install ClickHouse Client
      run: |
        sudo apt-get update
