name: Run ClickHouse SQL Scripts

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  run-sql:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: download ClickHouse locally
      run: |
        curl https://clickhouse.com/ | sh


    - name: connect to clickhouse client
      run: |
        ./clickhouse client --host gns0hl2of0.us-east-1.aws.clickhouse.cloud --secure --password 'z5KNWZt~yddf_'
        CREATE DATABASE db2
    - name: Run SQL Scripts
      run: |
        ./clickhouse client --query  'CREATE DATABASE db2'

    # CREATE TABLE my_table ( id UInt32, name String  ) ENGINE = MergeTree()  ORDER BY id;

    # for file in ./sql/*.sql; do
    #   clickhouse-client --host gns0hl2of0.us-east-1.aws --port 8443 --user default --password dQmdvuZ8Isw~t --query "$(cat $file)"
    # done

      # working-directory: $GITHUB_WORKSPACE